const students = [{
    "id": 1,
    "first_name": "Glenna",
    "last_name": "Deary",
    "email": "gdeary0@craigslist.org"
  }, {
    "id": 2,
    "first_name": "Kingston",
    "last_name": "Limbert",
    "email": "klimbert1@jalbum.net"
  }, {
    "id": 3,
    "first_name": "Eberto",
    "last_name": "Gridon",
    "email": "egridon2@biblegateway.com"
  }, {
    "id": 4,
    "first_name": "Sonni",
    "last_name": "Odney",
    "email": "sodney3@independent.co.uk"
  }, {
    "id": 5,
    "first_name": "Natala",
    "last_name": "Emerine",
    "email": "nemerine4@google.de"
  }, {
    "id": 6,
    "first_name": "Corey",
    "last_name": "Berriman",
    "email": "cberriman5@icio.us"
  }, {
    "id": 7,
    "first_name": "Samaria",
    "last_name": "Embling",
    "email": "sembling6@hugedomains.com"
  }, {
    "id": 8,
    "first_name": "York",
    "last_name": "Brittan",
    "email": "ybrittan7@plala.or.jp"
  }, {
    "id": 9,
    "first_name": "Chancey",
    "last_name": "Ruffli",
    "email": "cruffli8@answers.com"
  }, {
    "id": 10,
    "first_name": "Yehudi",
    "last_name": "Wormald",
    "email": "ywormald9@indiegogo.com"
  }]
  module.exports =students